### ISSUE TITLE
Record value doesn't change until shared variable is updated

### ISSUE THREAD

**Issue by geoffreyPerrin** [ISISComputingGroup/EPICS-NetShrVar#2]
Hi, 
If i start my IOC and the Shared Variable value doesn't change then my record value connected to this shared variable remain 0 even if the shared variable is not equal to 0. 
If i change the value of the shared variable with labView software or epics ouput record then my record value is updated.

**Comment by FreddieAkeroyd** [comment]
Hi, this seems to be a feature of shared variable subscriber connections - they do not give you an initial value. I will add a separate read on IOC startup.
