### ISSUE TITLE
Segmentation fault when using double array since last update

### ISSUE THREAD

**Issue by geoffreyPerrin** [ISISComputingGroup/EPICS-NetShrVar#4]
Hi,

I have an error when I try to read double array from LabView since the last update. At IOC boot just after the call to NetShrVarConfigure I have:
connectVars: connecting to ... // my first array
connectVars: connecting to ... // my second array
and then:

Sevr=fatal NetShrVarConfigure failed: CNVGetArrayDoubleValue: Argumentis invalid

After I have a segmentation fault. It worked fine with the older version.

Thanks for your help !
Geoffrey

**Comment by John-Holt-Tessella** [comment]
Hi, thank you for reporting this. We will look into this and fix it; I am not sure what the time scale for doing this will be.
Cheers,
John

**Comment by FreddieAkeroyd** [comment]
Hi @geoffreyPerrin I think the problem appeared as the network variable arrays were not initialised when the first read was made, so the code i added recently to do an initial read was throwing an error in this case. This isn't a problem in itself, but the exception wasn't caught at the right place meaning another part of NetShrVarConfigure didn't complete properly leading to the crash you saw. I've adjusted the exception handling, let me know if that sorts it out

**Comment by geoffreyPerrin** [comment]
Thank you ! It works now
